-- =============================================================================
-- M0 — Integration with external apps (Planivo HUB and future clients)
-- Single atomic migration. See INTEGRATION-PLAN.md sections 5.1–5.6.
--
-- Scope: schema only. NO edge functions (M1/M2), NO React/TS (M1/M3).
-- All new tables are scoped on account_id = auth.uid() of the HACCPrint owner,
-- consistent with the existing single-tenant-per-user schema.
-- All changes are ADDITIVE: no existing table changes shape except print_jobs
-- (ADD COLUMN only, with safe defaults / nullable).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 5.1 — connected_apps : registry of external apps connected to an account
-- -----------------------------------------------------------------------------
CREATE TABLE connected_apps (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_name      text NOT NULL,                 -- declared by the external app at /connect
  token_hash    text NOT NULL UNIQUE,          -- SHA-256 of the raw token (never the raw)
  token_prefix  text NOT NULL,                 -- e.g. "hcp_live_a1b2…" for the UI
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_used_at  timestamptz,                   -- updated on every authenticated request
  revoked_at    timestamptz                    -- soft revoke, NULL = active
);

-- org_name unique per account AMONG ACTIVE connections (product decision #2).
-- Partial index: the constraint applies only while revoked_at IS NULL.
CREATE UNIQUE INDEX connected_apps_active_org_unique
  ON connected_apps (account_id, org_name)
  WHERE revoked_at IS NULL;

-- -----------------------------------------------------------------------------
-- 5.2 — template_visibility : M:N between templates and connected apps
-- -----------------------------------------------------------------------------
CREATE TABLE template_visibility (
  template_id       uuid NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
  connected_app_id  uuid NOT NULL REFERENCES connected_apps(id) ON DELETE CASCADE,
  account_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,  -- denormalized for RLS
  created_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (template_id, connected_app_id)
);

-- -----------------------------------------------------------------------------
-- 5.3 — print_queue : queue of print jobs requested by external apps
-- -----------------------------------------------------------------------------
CREATE TABLE print_queue (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  connected_app_id  uuid REFERENCES connected_apps(id) ON DELETE SET NULL,
  org_name          text NOT NULL,             -- snapshot: survives revoke/rename
  template_id       uuid NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
  copies            int  NOT NULL DEFAULT 1 CHECK (copies >= 1 AND copies <= 200),
  prepared_date     date,                      -- default = today on the desktop if NULL
  idempotency_key   text NOT NULL,             -- anti-duplicate, generated by the external app
  status            text NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','printing','done','failed')),
  claimed_by        text,                      -- id of the desktop instance that claimed the job
  error             text,                      -- message if status='failed'
  created_at        timestamptz NOT NULL DEFAULT now(),
  printed_at        timestamptz                -- set on done/failed
);

-- Idempotency: same idempotency_key for the same account never creates duplicates.
CREATE UNIQUE INDEX print_queue_idem_unique
  ON print_queue (account_id, idempotency_key);

-- Fast lookup of pending jobs for the catch-up phase at startup.
CREATE INDEX print_queue_pending_idx
  ON print_queue (account_id, status)
  WHERE status = 'pending';

-- -----------------------------------------------------------------------------
-- 5.5 — index for "templates visible to org X" join
-- -----------------------------------------------------------------------------
CREATE INDEX template_visibility_app_idx
  ON template_visibility (connected_app_id);

-- -----------------------------------------------------------------------------
-- 5.6 — additive extension of existing print_jobs (HACCP compliance, decision #4)
-- Nullable / defaulted: historical rows and manual prints stay coherent, no data
-- migration needed, no breaking change to the v1.2.0 flow.
-- -----------------------------------------------------------------------------
ALTER TABLE print_jobs
  ADD COLUMN source           text NOT NULL DEFAULT 'desktop'  -- 'desktop' | 'api'
    CHECK (source IN ('desktop','api')),
  ADD COLUMN requested_by_org text;                            -- org_name, only for source='api'

-- -----------------------------------------------------------------------------
-- 5.4 — Row Level Security
-- Principle: RLS protects ONLY the owner's access (desktop + Settings UI +
-- LabelForm). External apps NEVER go through RLS — they enter only via edge
-- functions using service_role, which bypasses RLS by design.
-- -----------------------------------------------------------------------------
ALTER TABLE connected_apps      ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_visibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE print_queue         ENABLE ROW LEVEL SECURITY;

-- Single pattern for all three: the owner sees/manages only their own rows.
CREATE POLICY owner_all_connected_apps ON connected_apps
  FOR ALL USING (account_id = auth.uid()) WITH CHECK (account_id = auth.uid());

CREATE POLICY owner_all_template_visibility ON template_visibility
  FOR ALL USING (account_id = auth.uid()) WITH CHECK (account_id = auth.uid());

CREATE POLICY owner_all_print_queue ON print_queue
  FOR ALL USING (account_id = auth.uid()) WITH CHECK (account_id = auth.uid());

-- -----------------------------------------------------------------------------
-- 5.5 — Realtime publication
-- print_queue MUST be in the publication, otherwise the desktop listener
-- receives nothing. Easy to forget in deploy (risk #9).
-- -----------------------------------------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE print_queue;
